/*
 * Config.cpp
 *
 * Created: 23.02.2022 06:15:42
 *  Author: Michael
 */ 

#include "Config.h"

uint8_t au8ConfigIOPin[] = {
#ifdef CONFIG_RELAYMODULE
	CONFIG_IO_RELAYMODULE_K1,
	CONFIG_IO_RELAYMODULE_K2,
	#if (CONFIG_RELAYMODULE_IOS > 2)
		CONFIG_IO_RELAYMODULE_K3,
		CONFIG_IO_RELAYMODULE_K4,
	#endif
	#if (CONFIG_RELAYMODULE_IOS > 4)
		CONFIG_IO_RELAYMODULE_K5,
		CONFIG_IO_RELAYMODULE_K6,
		CONFIG_IO_RELAYMODULE_K7,
		CONFIG_IO_RELAYMODULE_K8,
	#endif /* CONFIG_RELAYMODULE_IOS == 8 */
#endif	/* CONFIG_RELAYMODULE */

#ifdef CONFIG_POWERSUPPLY
	CONFIG_IO_POWERSUPPLY_K1,
	CONFIG_IO_POWERSUPPLY_K2,
	#if (CONFIG_POWERSUPPLY_IOS > 2)
		CONFIG_IO_POWERSUPPLY_K3,
		CONFIG_IO_POWERSUPPLY_K4,
	#endif
	#if (CONFIG_POWERSUPPLY_IOS > 4)
		CONFIG_IO_POWERSUPPLY_K5,
		CONFIG_IO_POWERSUPPLY_K6,
		CONFIG_IO_POWERSUPPLY_K7,
		CONFIG_IO_POWERSUPPLY_K8,
	#endif /* CONFIG_POWERSUPPLY_IOS == 8 */
#endif /* CONFIG_POWERSUPPLY */
	0xFF
};

