//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCmanager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class DebugCtrl : global::System.Configuration.ApplicationSettingsBase {
        
        private static DebugCtrl defaultInstance = ((DebugCtrl)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DebugCtrl())));
        
        public static DebugCtrl Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugOn {
            get {
                return ((bool)(this["DebugOn"]));
            }
            set {
                this["DebugOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DebugFilter {
            get {
                return ((string)(this["DebugFilter"]));
            }
            set {
                this["DebugFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugFilterAddNext {
            get {
                return ((bool)(this["DebugFilterAddNext"]));
            }
            set {
                this["DebugFilterAddNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugAddFrameDelimiter {
            get {
                return ((bool)(this["DebugAddFrameDelimiter"]));
            }
            set {
                this["DebugAddFrameDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorInfoFG {
            get {
                return ((global::System.Drawing.Color)(this["ColorInfoFG"]));
            }
            set {
                this["ColorInfoFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorInfoBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorInfoBG"]));
            }
            set {
                this["ColorInfoBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorWarningFG {
            get {
                return ((global::System.Drawing.Color)(this["ColorWarningFG"]));
            }
            set {
                this["ColorWarningFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 192, 255")]
        public global::System.Drawing.Color ColorWarningBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorWarningBG"]));
            }
            set {
                this["ColorWarningBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorErrorFG {
            get {
                return ((global::System.Drawing.Color)(this["ColorErrorFG"]));
            }
            set {
                this["ColorErrorFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorErrorBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorErrorBG"]));
            }
            set {
                this["ColorErrorBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorSendFG {
            get {
                return ((global::System.Drawing.Color)(this["ColorSendFG"]));
            }
            set {
                this["ColorSendFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 216, 0")]
        public global::System.Drawing.Color ColorSendBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorSendBG"]));
            }
            set {
                this["ColorSendBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorReceiveFG {
            get {
                return ((global::System.Drawing.Color)(this["ColorReceiveFG"]));
            }
            set {
                this["ColorReceiveFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 106, 0")]
        public global::System.Drawing.Color ColorReceiveBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorReceiveBG"]));
            }
            set {
                this["ColorReceiveBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ListBoxWidth {
            get {
                return ((int)(this["ListBoxWidth"]));
            }
            set {
                this["ListBoxWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ListBoxWidthDefault {
            get {
                return ((int)(this["ListBoxWidthDefault"]));
            }
            set {
                this["ListBoxWidthDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1437226410")]
        public int InitCode {
            get {
                return ((int)(this["InitCode"]));
            }
            set {
                this["InitCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddTimeStamp {
            get {
                return ((bool)(this["AddTimeStamp"]));
            }
            set {
                this["AddTimeStamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddProjectsName {
            get {
                return ((bool)(this["AddProjectsName"]));
            }
            set {
                this["AddProjectsName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Debug.prj\"")]
        public string ProjectFile {
            get {
                return ((string)(this["ProjectFile"]));
            }
            set {
                this["ProjectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddApplication {
            get {
                return ((bool)(this["AddApplication"]));
            }
            set {
                this["AddApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Application {
            get {
                return ((string)(this["Application"]));
            }
            set {
                this["Application"] = value;
            }
        }
    }
}
