//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCmanager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class MonitoringSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MonitoringSettings defaultInstance = ((MonitoringSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MonitoringSettings())));
        
        public static MonitoringSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint InitCode {
            get {
                return ((uint)(this["InitCode"]));
            }
            set {
                this["InitCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] UserMonitoringTimeBase_ms {
            get {
                return ((int[])(this["UserMonitoringTimeBase_ms"]));
            }
            set {
                this["UserMonitoringTimeBase_ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public System.Drawing.Color[] LineColorRGB {
            get {
                return ((System.Drawing.Color[])(this["LineColorRGB"]));
            }
            set {
                this["LineColorRGB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[] UserMonitoring_Chart_1 {
            get {
                return ((bool[])(this["UserMonitoring_Chart_1"]));
            }
            set {
                this["UserMonitoring_Chart_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[] UserMonitoring_Chart_2 {
            get {
                return ((bool[])(this["UserMonitoring_Chart_2"]));
            }
            set {
                this["UserMonitoring_Chart_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] UserMonitoringSeries_Chart_1 {
            get {
                return ((int[])(this["UserMonitoringSeries_Chart_1"]));
            }
            set {
                this["UserMonitoringSeries_Chart_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] UserMonitoringSeries_Chart_2 {
            get {
                return ((int[])(this["UserMonitoringSeries_Chart_2"]));
            }
            set {
                this["UserMonitoringSeries_Chart_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Test {
            get {
                return ((bool)(this["Test"]));
            }
            set {
                this["Test"] = value;
            }
        }
    }
}
