//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCmanager.Properties
{
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class UserMonitoringSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserMonitoringSettings defaultInstance = ((UserMonitoringSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserMonitoringSettings())));
        
        public static UserMonitoringSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint InitCode {
            get {
                return ((uint)(this["InitCode"]));
            }
            set {
                this["InitCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ulong[] UserMonitoringTimeBase_ms {
            get {
                return ((ulong[])(this["UserMonitoringTimeBase_ms"]));
            }
            set {
                this["UserMonitoringTimeBase_ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool[,] UsedInChart {
            get {
                return ((bool[,])(this["UsedInChart"]));
            }
            set {
                this["UsedInChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Test {
            get {
                return ((bool)(this["Test"]));
            }
            set {
                this["Test"] = value;
            }
        }
    }
}
